version: '3'
x-environment: &default-environment
  environment:
    - TZ=Australia/Sydney

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 3000:3000
    <<: *default-environment
  test:
    build:
      context: .
      dockerfile: dockerfiles/test.dockerfile
    <<: *default-environment
    volumes:
      - './cypress/reports:/usr/src/app/cypress/reports'
    depends_on:
      - web
